### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by vsoft-phuong** [unbescape/unbescape#10]
Hi author!

I have:
{"GetMusicTempResult":"{\"ErrorCode\":0, \"ErrorMessage\":\"Thành Công\", \"Data\" : [{\"album_id\" : \"035BBCB36\",\"music_url\" : \"\/temp\/zmnepemsqntotmndhn2vstt5\/langletonthuong_mrsiro.mp3\",\"music_picture\" : \"\/PictureLip\/Album\/V-PopHotMp3Icon.png\",\"music_title\" : \" Lặng Lẽ Tổn Thương \",\"music_performers\" : \"Mr. Siro\",\"music_listen\" : \"265\",\"music_lyric\" : \"(Vậy mà em vẫn cứ ngây thơ<BR>Giờ đây em có vui đâu<BR>Vậy mà em vẫn cứ ngây thơ...)<BR><BR>Tại sao chúng mình, không nhận ra nhau sớm hơn<BR>Để anh có thể mạnh mẽ đến gần em, và<BR>Thì thầm lời hứa, em sẽ không phải khóc<BR>Chẳng như hôm nay, chỉ biết im lặng thôi<BR>Từ giây phút đầu, em nở nụ cười rất tươi<BR>Mà chỉ anh thấy, em vẫn không hạnh phúc, chút nào<BR>Và anh biết, người ở bên cạnh em bây giờ<BR>Không hề quan tâm đến cảm giác em như ngày xưa<BR><BR>ĐK1:<BR>Vậy mà vẫn cứ ngây thơ, em vẫn bên ai dại khờ<BR>Giờ đây em có vui đâu, xé nát tim anh nhiều lần<BR>Anh không chấp nhận nhìn em cố níu tay ai<BR>Anh xót xa trăm ngàn lần<BR>Tình yêu anh muốn trao em<BR>Nhưng chắc duyên ta phải dừng khi chưa bắt đầu<BR>Xin đừng để anh phải thấy em buồn<BR>(Xin đừng để anh phải thấy em buồn)<BR><BR>(Nhìn nụ cười buồn nở trên môi em, mà lòng này chợt nhận ra con tim, đã yêu em thật rồi<BR>When I see you cry, I love you more and more)<BR><BR>-----<BR>Bản thân anh đã nhiều lần tự hỏi<BR>Trong tim em anh chẳng là gì cả<BR>Sao phải quan tâm em quá như là<BR>\"Em xem anh là tất cả, niềm tin trong tim\"<BR>Nhưng khi anh chợt tỉnh giấc chỉ mình anh mơ<BR><BR>ĐK2:<BR>Vậy mà vẫn cứ ngây thơ, em vẫn bên ai dại khờ<BR>Giờ đây em có vui đâu, xé nát tim anh nhiều lần<BR>Anh không chấp nhận nhìn em cố níu tay ai<BR>Anh xót xa trăm ngàn lần<BR>Tình yêu anh muốn trao em<BR>Nhưng chắc duyên ta phải dừng khi chưa bắt đầu<BR>Xin đừng để anh phải thấy em buồn<BR>(Có lẽ đã không còn cần một người như anh để che chở)<BR><BR>(Và đừng quên anh từng ở bên em...) \",\"cat_id\" : \"1\",\"cat_name\" : \"V-Pop\",\"performers_id\" : \"C5E60D989\"}]}"}

After parse:
{"album_id" : "035BBCB36","music_url" : "/temp/unnxccplluaogwx01dckf5en/langletonthuong_mrsiro.mp3","music_picture" : "/PictureLip/Album/V-PopHotMp3Icon.png","music_title" : " Lặng Lẽ Tổn Thương ","music_performers" : "Mr. Siro","music_listen" : "266","music_lyric" : "(Vậy mà em vẫn cứ ngây thơ<BR>Giờ đây em có vui đâu<BR>Vậy mà em vẫn cứ ngây thơ...)<BR><BR>Tại sao chúng mình, không nhận ra nhau sớm hơn<BR>Để anh có thể mạnh mẽ đến gần em, và<BR>Thì thầm lời hứa, em sẽ không phải khóc<BR>Chẳng như hôm nay, chỉ biết im lặng thôi<BR>Từ giây phút đầu, em nở nụ cười rất tươi<BR>Mà chỉ anh thấy, em vẫn không hạnh phúc, chút nào<BR>Và anh biết, người ở bên cạnh em bây giờ<BR>Không hề quan tâm đến cảm giác em như ngày xưa<BR><BR>ĐK1:<BR>Vậy mà vẫn cứ ngây thơ, em vẫn bên ai dại khờ<BR>Giờ đây em có vui đâu, xé nát tim anh nhiều lần<BR>Anh không chấp nhận nhìn em cố níu tay ai<BR>Anh xót xa trăm ngàn lần<BR>Tình yêu anh muốn trao em<BR>Nhưng chắc duyên ta phải dừng khi chưa bắt đầu<BR>Xin đừng để anh phải thấy em buồn<BR>(Xin đừng để anh phải thấy em buồn)<BR><BR>(Nhìn nụ cười buồn nở trên môi em, mà lòng này chợt nhận ra con tim, đã yêu em thật rồi<BR>When I see you cry, I love you more and more)<BR><BR>-----<BR>Bản thân anh đã nhiều lần tự hỏi<BR>Trong tim em anh chẳng là gì cả<BR>Sao phải quan tâm em quá như là<BR>\"Em xem anh là tất cả, niềm tin trong tim\"<BR>Nhưng khi anh chợt tỉnh giấc chỉ mình anh mơ<BR><BR>ĐK2:<BR>Vậy mà vẫn cứ ngây thơ, em vẫn bên ai dại khờ<BR>Giờ đây em có vui đâu, xé nát tim anh nhiều lần<BR>Anh không chấp nhận nhìn em cố níu tay ai<BR>Anh xót xa trăm ngàn lần<BR>Tình yêu anh muốn trao em<BR>Nhưng chắc duyên ta phải dừng khi chưa bắt đầu<BR>Xin đừng để anh phải thấy em buồn<BR>(Có lẽ đã không còn cần một người như anh để che chở)<BR><BR>(Và đừng quên anh từng ở bên em...) ","cat_id" : "1","cat_name" : "V-Pop","performers_id" : "C5E60D989"}

Error is: "Em xem anh là tất cả, niềm tin trong tim"
Please fix library to parse: \"Em xem anh là tất cả, niềm tin trong tim\"
Check json by: http://jsonlint.com/

Thanks!
![error_15_5_2015](https://cloud.githubusercontent.com/assets/1147284/7646461/1cca73f8-faee-11e4-8227-2ea59e4dd388.PNG)

**Comment by danielfernandez** [comment]
Sorry, I don't completely understand the problem. Please note that Unbescape is not a JSON parsing library, but a library able to escape or unescape JSON literals. This is, just the literals. It shouldn't do anything especially useful with a whole JSON object...

Are there any specific characters or unicode codepoints that are not being correctly escaped or unescaped in your code?

**Comment by vsoft-phuong** [comment]
Hi!

I use your library to unescape json, it is very good. In case, content of
attribute(music_lyric) have double quote ("), raw json return \" is
correct, your library replaced \" to " .
So it wrong.
Please see attach file.
Thanks!

On Fri, May 15, 2015 at 2:27 PM, Daniel Fernández <notifications@github.com>
wrote:

> Sorry, I don't completely understand the problem. Please note that
> Unbescape is not a JSON parsing library, but a library able to escape or
> unescape JSON literals. This is, just the literals. It shouldn't do
> anything especially useful with a whole JSON object...
>
> Are there any specific characters or unicode codepoints that are not being
> correctly escaped or unescaped in your code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/unbescape/unbescape/issues/10#issuecomment-102298537>.
>

{"GetMusicTempResult":"{\"ErrorCode\":0, \"ErrorMessage\":\"Thành Công\", \"Data\" : [{\"album_id\" : \"035BBCB36\",\"music_url\" : \"\/temp\/zmnepemsqntotmndhn2vstt5\/langletonthuong_mrsiro.mp3\",\"music_picture\" : \"\/PictureLip\/Album\/V-PopHotMp3Icon.png\",\"music_title\" : \" Lặng Lẽ Tổn Thương \",\"music_performers\" : \"Mr. Siro\",\"music_listen\" : \"265\",\"music_lyric\" : \"(Vậy mà em vẫn cứ ngây thơ<BR>Giờ đây em có vui đâu<BR>Vậy mà em vẫn cứ ngây thơ...)<BR><BR>Tại sao chúng mình, không nhận ra nhau sớm hơn<BR>Để anh có thể mạnh mẽ đến gần em, và<BR>Thì thầm lời hứa, em sẽ không phải khóc<BR>Chẳng như hôm nay, chỉ biết im lặng thôi<BR>Từ giây phút đầu, em nở nụ cười rất tươi<BR>Mà chỉ anh thấy, em vẫn không hạnh phúc, chút nào<BR>Và anh biết, người ở bên cạnh em bây giờ<BR>Không hề quan tâm đến cảm giác em như ngày xưa<BR><BR>ĐK1:<BR>Vậy mà vẫn cứ ngây thơ, em vẫn bên ai dại khờ<BR>Giờ đây em có vui đâu, xé nát tim anh nhiều lần<BR>Anh không chấp nhận nhìn em cố níu tay ai<BR>Anh xót xa trăm ngàn lần<BR>Tình yêu anh muốn trao em<BR>Nhưng chắc duyên ta phải dừng khi chưa bắt đầu<BR>Xin đừng để anh phải thấy em buồn<BR>(Xin đừng để anh phải thấy em buồn)<BR><BR>(Nhìn nụ cười buồn nở trên môi em, mà lòng này chợt nhận ra con tim, đã yêu em thật rồi<BR>When I see you cry, I love you more and more)<BR><BR>-----<BR>Bản thân anh đã nhiều lần tự hỏi<BR>Trong tim em anh chẳng là gì cả<BR>Sao phải quan tâm em quá như là<BR>\"Em xem anh là tất cả, niềm tin trong tim\"<BR>Nhưng khi anh chợt tỉnh giấc chỉ mình anh mơ<BR><BR>ĐK2:<BR>Vậy mà vẫn cứ ngây thơ, em vẫn bên ai dại khờ<BR>Giờ đây em có vui đâu, xé nát tim anh nhiều lần<BR>Anh không chấp nhận nhìn em cố níu tay ai<BR>Anh xót xa trăm ngàn lần<BR>Tình yêu anh muốn trao em<BR>Nhưng chắc duyên ta phải dừng khi chưa bắt đầu<BR>Xin đừng để anh phải thấy em buồn<BR>(Có lẽ đã không còn cần một người như anh để che chở)<BR><BR>(Và đừng quên anh từng ở bên em...) \",\"cat_id\" : \"1\",\"cat_name\" : \"V-Pop\",\"performers_id\" : \"C5E60D989\"}]}"}

Error:
{"album_id" : "035BBCB36","music_url" : "/temp/unnxccplluaogwx01dckf5en/langletonthuong_mrsiro.mp3","music_picture" : "/PictureLip/Album/V-PopHotMp3Icon.png","music_title" : " Lặng Lẽ Tổn Thương ","music_performers" : "Mr. Siro","music_listen" : "266","music_lyric" : "(Vậy mà em vẫn cứ ngây thơ<BR>Giờ đây em có vui đâu<BR>Vậy mà em vẫn cứ ngây thơ...)<BR><BR>Tại sao chúng mình, không nhận ra nhau sớm hơn<BR>Để anh có thể mạnh mẽ đến gần em, và<BR>Thì thầm lời hứa, em sẽ không phải khóc<BR>Chẳng như hôm nay, chỉ biết im lặng thôi<BR>Từ giây phút đầu, em nở nụ cười rất tươi<BR>Mà chỉ anh thấy, em vẫn không hạnh phúc, chút nào<BR>Và anh biết, người ở bên cạnh em bây giờ<BR>Không hề quan tâm đến cảm giác em như ngày xưa<BR><BR>ĐK1:<BR>Vậy mà vẫn cứ ngây thơ, em vẫn bên ai dại khờ<BR>Giờ đây em có vui đâu, xé nát tim anh nhiều lần<BR>Anh không chấp nhận nhìn em cố níu tay ai<BR>Anh xót xa trăm ngàn lần<BR>Tình yêu anh muốn trao em<BR>Nhưng chắc duyên ta phải dừng khi chưa bắt đầu<BR>Xin đừng để anh phải thấy em buồn<BR>(Xin đừng để anh phải thấy em buồn)<BR><BR>(Nhìn nụ cười buồn nở trên môi em, mà lòng này chợt nhận ra con tim, đã yêu em thật rồi<BR>When I see you cry, I love you more and more)<BR><BR>-----<BR>Bản thân anh đã nhiều lần tự hỏi<BR>Trong tim em anh chẳng là gì cả<BR>Sao phải quan tâm em quá như là<BR>\"Em xem anh là tất cả, niềm tin trong tim\"<BR>Nhưng khi anh chợt tỉnh giấc chỉ mình anh mơ<BR><BR>ĐK2:<BR>Vậy mà vẫn cứ ngây thơ, em vẫn bên ai dại khờ<BR>Giờ đây em có vui đâu, xé nát tim anh nhiều lần<BR>Anh không chấp nhận nhìn em cố níu tay ai<BR>Anh xót xa trăm ngàn lần<BR>Tình yêu anh muốn trao em<BR>Nhưng chắc duyên ta phải dừng khi chưa bắt đầu<BR>Xin đừng để anh phải thấy em buồn<BR>(Có lẽ đã không còn cần một người như anh để che chở)<BR><BR>(Và đừng quên anh từng ở bên em...) ","cat_id" : "1","cat_name" : "V-Pop","performers_id" : "C5E60D989"}

Correct:
{"album_id" : "035BBCB36","music_url" : "/temp/unnxccplluaogwx01dckf5en/langletonthuong_mrsiro.mp3","music_picture" : "/PictureLip/Album/V-PopHotMp3Icon.png","music_title" : " Lặng Lẽ Tổn Thương ","music_performers" : "Mr. Siro","music_listen" : "266","music_lyric" : "(Vậy mà em vẫn cứ ngây thơ<BR>Giờ đây em có vui đâu<BR>Vậy mà em vẫn cứ ngây thơ...)<BR><BR>Tại sao chúng mình, không nhận ra nhau sớm hơn<BR>Để anh có thể mạnh mẽ đến gần em, và<BR>Thì thầm lời hứa, em sẽ không phải khóc<BR>Chẳng như hôm nay, chỉ biết im lặng thôi<BR>Từ giây phút đầu, em nở nụ cười rất tươi<BR>Mà chỉ anh thấy, em vẫn không hạnh phúc, chút nào<BR>Và anh biết, người ở bên cạnh em bây giờ<BR>Không hề quan tâm đến cảm giác em như ngày xưa<BR><BR>ĐK1:<BR>Vậy mà vẫn cứ ngây thơ, em vẫn bên ai dại khờ<BR>Giờ đây em có vui đâu, xé nát tim anh nhiều lần<BR>Anh không chấp nhận nhìn em cố níu tay ai<BR>Anh xót xa trăm ngàn lần<BR>Tình yêu anh muốn trao em<BR>Nhưng chắc duyên ta phải dừng khi chưa bắt đầu<BR>Xin đừng để anh phải thấy em buồn<BR>(Xin đừng để anh phải thấy em buồn)<BR><BR>(Nhìn nụ cười buồn nở trên môi em, mà lòng này chợt nhận ra con tim, đã yêu em thật rồi<BR>When I see you cry, I love you more and more)<BR><BR>-----<BR>Bản thân anh đã nhiều lần tự hỏi<BR>Trong tim em anh chẳng là gì cả<BR>Sao phải quan tâm em quá như là<BR>\"Em xem anh là tất cả, niềm tin trong tim\"<BR>Nhưng khi anh chợt tỉnh giấc chỉ mình anh mơ<BR><BR>ĐK2:<BR>Vậy mà vẫn cứ ngây thơ, em vẫn bên ai dại khờ<BR>Giờ đây em có vui đâu, xé nát tim anh nhiều lần<BR>Anh không chấp nhận nhìn em cố níu tay ai<BR>Anh xót xa trăm ngàn lần<BR>Tình yêu anh muốn trao em<BR>Nhưng chắc duyên ta phải dừng khi chưa bắt đầu<BR>Xin đừng để anh phải thấy em buồn<BR>(Có lẽ đã không còn cần một người như anh để che chở)<BR><BR>(Và đừng quên anh từng ở bên em...) ","cat_id" : "1","cat_name" : "V-Pop","performers_id" : "C5E60D989"}

Error is: "Em xem anh là tất cả, niềm tin trong tim"
Please fix library to parse: \"Em xem anh là tất cả, niềm tin trong tim\"
Check json by: http://jsonlint.com/

**Comment by danielfernandez** [comment]
I cannot see any attached files on github, sorry. 

However, in the code I can see above you don't have a `music_lyric` attribute. Your JSON structure above only has one attribute called `GetMusicTempResult`, and the rest of the JSON is the value of such attribute. 

Such value of `GetMusicTempResult` starts with `{\"ErrorCode\":0` and ends with `\"performers_id\" : \"C5E60D989\"}]}`. It seems to be another JSON structure, written there as a mere JSON literal, but incorrectly escaped. That JSON structure seems to have several attributes, one of which is your `music_lyric`. but inside that attribute there is your `\"Em xem anh là tất cả, niềm tin trong tim\"` which is surrounded by `\"` instead of the correct `\\"`, which is what you should have because you are going to perform two unescape operations on that: one on the first-level literal (the value of `GetMusicTempResult` and another one once you parse the value of `GetMusicTempResult` as another JSON structure.

I'm afraid Unbescape is doing its job correctly, therefore. The error seems to be in your JSON code.

**Comment by vsoft-phuong** [comment]
OK, thanks!
