### ISSUE TITLE
org.unbescape.uri.UriEscape should supports escape '

### ISSUE THREAD

**Issue by myvyang** [unbescape/unbescape#13]
As many persons write code like:

```
<a href='http://my/input/url'>
```

It's not security after ignore `'`, thought the RFC define this.

**Comment by danielfernandez** [comment]
Thanks. However, in a scenario such as the one you mention, there are two escapes to be done, not one.

First, `UriEscape` should take care of correctly URI-escaping the URL. But then if that URL is to be used in an HTML attribute like the one you put as an example, an additional HTML-escape operation should be done as with any values of any HTML attributes. And it's this HTML-escape operation that would take care of any value-closing apostrophe symbols (`'`).
