### ISSUE TITLE
unescapeHtml does not replace &nbsp with white space

### ISSUE THREAD

**Issue by dabeschte** [unbescape/unbescape#16]
&nbsp stays unchanged in resulting unescaped text

**Comment by danielfernandez** [comment]
Confirmed to be a bug. Apparently the `HtmlEscapeSymbols#binarySearch(...)` methods are not properly doing their job when reporting about partial matches, and this provokes some misses when unescaping those NCRs that are supported to be unescaped even if their final `;` symbol is missing.

**Comment by danielfernandez** [comment]
Already in `1.1.5-SNAPSHOT`
